In [1]:
import json, os
import pandas as pd
import numpy as np
from Module.utils.Convenience_Function import read_json

In [2]:
PARENTS_PATH = "Log/Train_Log"
log_list = os.listdir(PARENTS_PATH)
log_list

['.ipynb_checkpoints',
 'retinaNet_resnet50_v2_1_0.json',
 'retinaNet_resnet50_v2_2_0.json',
 'retinaNet_resnet50_v2_0_0.json',
 'retinaNet_resnet50_v2_3_0.json']

In [3]:
gpu0_log_path = f"{PARENTS_PATH}/{log_list[3]}"
gpu1_log_path = f"{PARENTS_PATH}/{log_list[1]}"
gpu2_log_path = f"{PARENTS_PATH}/{log_list[2]}"
gpu3_log_path = f"{PARENTS_PATH}/{log_list[4]}"

In [4]:
def get_log_df(log_path):
    
    score_columns = ["train_total", "valid_total", "AP(AP@[.50:.05:.95])","AP50","AP75","precision","recall","f1_score"]
    
    json_data = read_json(log_path)
    log_df = pd.DataFrame(json_data)
    
    loss_df = log_df[list(set(log_df.columns) - set(score_columns))].reset_index(drop=True)
    score_df = log_df[score_columns].reset_index(drop=True)
    
    check_early_stopping(score_df)
    
    return score_df, loss_df



def check_early_stopping(log_df, key="valid_total", ascending=False):
    
    target_list = log_df[key].to_list()
    # 시작 지점
    before_score = target_list[0] if ascending else -target_list[0]
    stack_list = [True]

    for now_score in target_list[1:]:

        now_score = now_score if ascending else -now_score

        if now_score > before_score:
            stack_list.append(True)
            before_score = now_score
        else:
            stack_list.append(False)
            
    log_df['early_stop'] = stack_list

In [5]:
gpu0_df, _ = get_log_df(log_path=gpu0_log_path)
gpu1_df, _ = get_log_df(log_path=gpu1_log_path)
gpu2_df, _ = get_log_df(log_path=gpu2_log_path)
gpu3_df, _ = get_log_df(log_path=gpu3_log_path)

In [6]:
gpu0_df

,train_total,valid_total,AP(AP@[.50:.05:.95]),AP50,AP75,precision,recall,f1_score,early_stop
0,0.191918,0.066722,0.683328,0.905124,0.834478,0.993773,0.907850,0.948870,True
1,0.096920,0.057959,0.703456,0.902532,0.852067,0.996238,0.904382,0.948091,True
2,0.093715,0.093904,0.743677,0.974315,0.890014,0.989631,0.977247,0.983400,False
3,0.079131,0.046937,0.762280,0.973174,0.913883,0.995925,0.974374,0.985032,True
4,0.082444,0.067478,0.733720,0.963113,0.890613,0.985541,0.964892,0.975107,False
...,...,...,...,...,...,...,...,...,...
58,0.053011,0.041196,0.751363,0.916307,0.891788,0.998141,0.917426,0.956083,False
59,0.051761,0.050290,0.789752,0.962605,0.933082,0.997055,0.964123,0.980313,False
60,0.050520,0.040457,0.784869,0.955795,0.928282,0.999405,0.956720,0.977597,False
61,0.048365,0.039445,0.774950,0.947120,0.919684,0.998800,0.948178,0.972831,False
62,0.050569,0.040864,0.777757,0.948137,0.920450,0.997606,0.949317,0.972863,False

In [7]:
gpu1_df

,train_total,valid_total,AP(AP@[.50:.05:.95]),AP50,AP75,precision,recall,f1_score,early_stop
0,0.152827,0.063416,0.667365,0.887895,0.813218,0.994271,0.889522,0.938984,True
1,0.097726,0.063882,0.692579,0.898935,0.836354,0.995595,0.900398,0.945607,False
2,0.091630,0.074388,0.747536,0.958758,0.904817,0.996456,0.960159,0.977971,False
3,0.080005,0.052240,0.753222,0.961772,0.898740,0.994121,0.962984,0.978305,True
4,0.082793,0.061885,0.741071,0.972982,0.888081,0.995923,0.973804,0.984739,False
...,...,...,...,...,...,...,...,...,...
58,0.049865,0.040176,0.768376,0.938828,0.908373,0.998789,0.939636,0.968310,False
59,0.049401,0.043320,0.792478,0.968335,0.936055,0.998826,0.969248,0.983815,False
60,0.048395,0.041153,0.790375,0.966310,0.932288,0.999411,0.966970,0.982923,False
61,0.046744,0.040750,0.780197,0.953244,0.921943,0.999403,0.953872,0.976107,False
62,0.048215,0.043658,0.779619,0.949560,0.920984,0.998206,0.950456,0.973746,False

In [8]:
gpu2_df

,train_total,valid_total,AP(AP@[.50:.05:.95]),AP50,AP75,precision,recall,f1_score,early_stop
0,0.233168,0.074607,0.542814,0.766803,0.636791,0.996310,0.768793,0.867888,True
1,0.148016,0.071929,0.594499,0.800299,0.711198,0.998582,0.801366,0.889170,True
2,NaN,0.270241,0.098359,0.162669,0.113979,0.813333,0.173493,0.285982,False

In [9]:
gpu3_df

,train_total,valid_total,AP(AP@[.50:.05:.95]),AP50,AP75,precision,recall,f1_score,early_stop
0,0.612976,0.353483,0.002603,0.012357,0.000332,0.346320,0.045455,0.080362,True
1,0.411650,0.287885,0.031789,0.073034,0.027299,0.646643,0.104155,0.179412,True
2,0.363286,0.251321,0.047096,0.098457,0.042999,0.728188,0.123295,0.210884,True
3,0.316400,0.233005,0.072373,0.145253,0.065798,0.736973,0.166948,0.272227,True
4,0.314971,0.222698,0.088016,0.183408,0.083781,0.686456,0.206358,0.317324,True
...,...,...,...,...,...,...,...,...,...
121,0.123429,0.081884,0.518029,0.753853,0.623634,0.959770,0.759091,0.847716,False
122,0.121098,0.081504,0.527297,0.766408,0.635409,0.957042,0.772159,0.854717,False
123,0.124563,0.081441,0.526382,0.765999,0.633661,0.957012,0.771591,0.854357,False
124,0.119588,0.081506,0.518755,0.754677,0.627416,0.955032,0.760227,0.846568,False
125,0.121620,0.080938,0.529803,0.773478,0.636349,0.955463,0.779671,0.858662,True