In [1]:
import pandas as pd
import numpy as np

from Module.utils.Convenience_Function import read_json

In [10]:
log_file_path = "Log/Iter_Log/model_training_log_3_0.json"

In [11]:
pd.DataFrame(read_json(log_file_path))

     epoch  iteration          lr         eta     elapsed    load iter_train
0        0          0  0.00009938  1:37:47.51  0:00:05.27  4.2584     1.0134
1        0          5  0.00007939  0:31:44.79  0:00:10.31  1.6893     0.3188
2        0         10  0.00004218  0:22:50.43  0:00:13.66  0.0021     0.4166
3        0         15  0.00000956  0:20:08.88  0:00:17.61  0.0009     0.3115
4        0         20  0.00009985  0:14:34.30  0:00:21.27  0.0022     0.3237
..     ...        ...         ...         ...         ...     ...        ...
345      1        605  0.00007138  0:07:01.66  0:09:05.74  0.0022     0.3109
346      1        610  0.00007082  0:07:00.52  0:09:09.81  0.0806     0.3065
347      1        615  0.00007027  0:07:23.84  0:09:15.69  1.6851     0.3195
348      1        620  0.00006970  0:06:50.87  0:09:19.88  0.0022     0.3101
349      1        625  0.00006914  0:07:26.37  0:09:24.03  0.0020     0.3137

[350 rows x 7 columns]